name: Test & release

on:
  pull_request:
  push:
    branches:
      - master
      - v11

jobs:
  validate:
    name: Build and test
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v5

      - name: ⎔ Setup node
        uses: actions/setup-node@v6
        with:
          node-version: ${{ github.ref == 'refs/heads/v11' && 8 || 18 }}
          cache: 'npm'

      - name: 📥 Download deps
        run: npm ci

      - name: ▶️ Run tests
        run: npm test
        env:
          BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USER }}
          BROWSERSTACK_KEY: ${{ secrets.BROWSERSTACK_KEY }}
